# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: term_score.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='term_score.proto',
  package='model',
  serialized_pb='\n\x10term_score.proto\x12\x05model\"(\n\tTermScore\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05score\x18\x02 \x02(\x05\"7\n\x10TermScoreDataset\x12#\n\ttermScore\x18\x01 \x03(\x0b\x32\x10.model.TermScoreB\"\n\x0f\x63om.gtech.modelB\x0fTermScoreProtos')




_TERMSCORE = _descriptor.Descriptor(
  name='TermScore',
  full_name='model.TermScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='model.TermScore.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='model.TermScore.score', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=67,
)


_TERMSCOREDATASET = _descriptor.Descriptor(
  name='TermScoreDataset',
  full_name='model.TermScoreDataset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='termScore', full_name='model.TermScoreDataset.termScore', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=69,
  serialized_end=124,
)

_TERMSCOREDATASET.fields_by_name['termScore'].message_type = _TERMSCORE
DESCRIPTOR.message_types_by_name['TermScore'] = _TERMSCORE
DESCRIPTOR.message_types_by_name['TermScoreDataset'] = _TERMSCOREDATASET

class TermScore(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TERMSCORE

  # @@protoc_insertion_point(class_scope:model.TermScore)

class TermScoreDataset(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TERMSCOREDATASET

  # @@protoc_insertion_point(class_scope:model.TermScoreDataset)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\017com.gtech.modelB\017TermScoreProtos')
# @@protoc_insertion_point(module_scope)
