// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: term_score.proto

package com.gtech.model;

public final class TermScoreProtos {
  private TermScoreProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TermScoreOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required int32 score = 2;
    /**
     * <code>required int32 score = 2;</code>
     */
    boolean hasScore();
    /**
     * <code>required int32 score = 2;</code>
     */
    int getScore();
  }
  /**
   * Protobuf type {@code model.TermScore}
   */
  public static final class TermScore extends
      com.google.protobuf.GeneratedMessage
      implements TermScoreOrBuilder {
    // Use TermScore.newBuilder() to construct.
    private TermScore(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TermScore(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TermScore defaultInstance;
    public static TermScore getDefaultInstance() {
      return defaultInstance;
    }

    public TermScore getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TermScore(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              score_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gtech.model.TermScoreProtos.internal_static_model_TermScore_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gtech.model.TermScoreProtos.internal_static_model_TermScore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gtech.model.TermScoreProtos.TermScore.class, com.gtech.model.TermScoreProtos.TermScore.Builder.class);
    }

    public static com.google.protobuf.Parser<TermScore> PARSER =
        new com.google.protobuf.AbstractParser<TermScore>() {
      public TermScore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TermScore(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TermScore> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 score = 2;
    public static final int SCORE_FIELD_NUMBER = 2;
    private int score_;
    /**
     * <code>required int32 score = 2;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 score = 2;</code>
     */
    public int getScore() {
      return score_;
    }

    private void initFields() {
      name_ = "";
      score_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, score_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, score_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gtech.model.TermScoreProtos.TermScore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gtech.model.TermScoreProtos.TermScore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gtech.model.TermScoreProtos.TermScore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gtech.model.TermScoreProtos.TermScore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gtech.model.TermScoreProtos.TermScore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gtech.model.TermScoreProtos.TermScore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gtech.model.TermScoreProtos.TermScore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gtech.model.TermScoreProtos.TermScore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gtech.model.TermScoreProtos.TermScore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gtech.model.TermScoreProtos.TermScore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gtech.model.TermScoreProtos.TermScore prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.TermScore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gtech.model.TermScoreProtos.TermScoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gtech.model.TermScoreProtos.internal_static_model_TermScore_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gtech.model.TermScoreProtos.internal_static_model_TermScore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gtech.model.TermScoreProtos.TermScore.class, com.gtech.model.TermScoreProtos.TermScore.Builder.class);
      }

      // Construct using com.gtech.model.TermScoreProtos.TermScore.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gtech.model.TermScoreProtos.internal_static_model_TermScore_descriptor;
      }

      public com.gtech.model.TermScoreProtos.TermScore getDefaultInstanceForType() {
        return com.gtech.model.TermScoreProtos.TermScore.getDefaultInstance();
      }

      public com.gtech.model.TermScoreProtos.TermScore build() {
        com.gtech.model.TermScoreProtos.TermScore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gtech.model.TermScoreProtos.TermScore buildPartial() {
        com.gtech.model.TermScoreProtos.TermScore result = new com.gtech.model.TermScoreProtos.TermScore(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gtech.model.TermScoreProtos.TermScore) {
          return mergeFrom((com.gtech.model.TermScoreProtos.TermScore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gtech.model.TermScoreProtos.TermScore other) {
        if (other == com.gtech.model.TermScoreProtos.TermScore.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasScore()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gtech.model.TermScoreProtos.TermScore parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gtech.model.TermScoreProtos.TermScore) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required int32 score = 2;
      private int score_ ;
      /**
       * <code>required int32 score = 2;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 score = 2;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>required int32 score = 2;</code>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 score = 2;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:model.TermScore)
    }

    static {
      defaultInstance = new TermScore(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:model.TermScore)
  }

  public interface TermScoreDatasetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .model.TermScore termScore = 1;
    /**
     * <code>repeated .model.TermScore termScore = 1;</code>
     */
    java.util.List<com.gtech.model.TermScoreProtos.TermScore> 
        getTermScoreList();
    /**
     * <code>repeated .model.TermScore termScore = 1;</code>
     */
    com.gtech.model.TermScoreProtos.TermScore getTermScore(int index);
    /**
     * <code>repeated .model.TermScore termScore = 1;</code>
     */
    int getTermScoreCount();
    /**
     * <code>repeated .model.TermScore termScore = 1;</code>
     */
    java.util.List<? extends com.gtech.model.TermScoreProtos.TermScoreOrBuilder> 
        getTermScoreOrBuilderList();
    /**
     * <code>repeated .model.TermScore termScore = 1;</code>
     */
    com.gtech.model.TermScoreProtos.TermScoreOrBuilder getTermScoreOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code model.TermScoreDataset}
   */
  public static final class TermScoreDataset extends
      com.google.protobuf.GeneratedMessage
      implements TermScoreDatasetOrBuilder {
    // Use TermScoreDataset.newBuilder() to construct.
    private TermScoreDataset(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TermScoreDataset(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TermScoreDataset defaultInstance;
    public static TermScoreDataset getDefaultInstance() {
      return defaultInstance;
    }

    public TermScoreDataset getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TermScoreDataset(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                termScore_ = new java.util.ArrayList<com.gtech.model.TermScoreProtos.TermScore>();
                mutable_bitField0_ |= 0x00000001;
              }
              termScore_.add(input.readMessage(com.gtech.model.TermScoreProtos.TermScore.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          termScore_ = java.util.Collections.unmodifiableList(termScore_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gtech.model.TermScoreProtos.internal_static_model_TermScoreDataset_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gtech.model.TermScoreProtos.internal_static_model_TermScoreDataset_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gtech.model.TermScoreProtos.TermScoreDataset.class, com.gtech.model.TermScoreProtos.TermScoreDataset.Builder.class);
    }

    public static com.google.protobuf.Parser<TermScoreDataset> PARSER =
        new com.google.protobuf.AbstractParser<TermScoreDataset>() {
      public TermScoreDataset parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TermScoreDataset(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TermScoreDataset> getParserForType() {
      return PARSER;
    }

    // repeated .model.TermScore termScore = 1;
    public static final int TERMSCORE_FIELD_NUMBER = 1;
    private java.util.List<com.gtech.model.TermScoreProtos.TermScore> termScore_;
    /**
     * <code>repeated .model.TermScore termScore = 1;</code>
     */
    public java.util.List<com.gtech.model.TermScoreProtos.TermScore> getTermScoreList() {
      return termScore_;
    }
    /**
     * <code>repeated .model.TermScore termScore = 1;</code>
     */
    public java.util.List<? extends com.gtech.model.TermScoreProtos.TermScoreOrBuilder> 
        getTermScoreOrBuilderList() {
      return termScore_;
    }
    /**
     * <code>repeated .model.TermScore termScore = 1;</code>
     */
    public int getTermScoreCount() {
      return termScore_.size();
    }
    /**
     * <code>repeated .model.TermScore termScore = 1;</code>
     */
    public com.gtech.model.TermScoreProtos.TermScore getTermScore(int index) {
      return termScore_.get(index);
    }
    /**
     * <code>repeated .model.TermScore termScore = 1;</code>
     */
    public com.gtech.model.TermScoreProtos.TermScoreOrBuilder getTermScoreOrBuilder(
        int index) {
      return termScore_.get(index);
    }

    private void initFields() {
      termScore_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getTermScoreCount(); i++) {
        if (!getTermScore(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < termScore_.size(); i++) {
        output.writeMessage(1, termScore_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < termScore_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, termScore_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gtech.model.TermScoreProtos.TermScoreDataset parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gtech.model.TermScoreProtos.TermScoreDataset parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gtech.model.TermScoreProtos.TermScoreDataset parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gtech.model.TermScoreProtos.TermScoreDataset parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gtech.model.TermScoreProtos.TermScoreDataset parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gtech.model.TermScoreProtos.TermScoreDataset parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gtech.model.TermScoreProtos.TermScoreDataset parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gtech.model.TermScoreProtos.TermScoreDataset parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gtech.model.TermScoreProtos.TermScoreDataset parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gtech.model.TermScoreProtos.TermScoreDataset parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gtech.model.TermScoreProtos.TermScoreDataset prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.TermScoreDataset}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gtech.model.TermScoreProtos.TermScoreDatasetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gtech.model.TermScoreProtos.internal_static_model_TermScoreDataset_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gtech.model.TermScoreProtos.internal_static_model_TermScoreDataset_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gtech.model.TermScoreProtos.TermScoreDataset.class, com.gtech.model.TermScoreProtos.TermScoreDataset.Builder.class);
      }

      // Construct using com.gtech.model.TermScoreProtos.TermScoreDataset.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTermScoreFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (termScoreBuilder_ == null) {
          termScore_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          termScoreBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gtech.model.TermScoreProtos.internal_static_model_TermScoreDataset_descriptor;
      }

      public com.gtech.model.TermScoreProtos.TermScoreDataset getDefaultInstanceForType() {
        return com.gtech.model.TermScoreProtos.TermScoreDataset.getDefaultInstance();
      }

      public com.gtech.model.TermScoreProtos.TermScoreDataset build() {
        com.gtech.model.TermScoreProtos.TermScoreDataset result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gtech.model.TermScoreProtos.TermScoreDataset buildPartial() {
        com.gtech.model.TermScoreProtos.TermScoreDataset result = new com.gtech.model.TermScoreProtos.TermScoreDataset(this);
        int from_bitField0_ = bitField0_;
        if (termScoreBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            termScore_ = java.util.Collections.unmodifiableList(termScore_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.termScore_ = termScore_;
        } else {
          result.termScore_ = termScoreBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gtech.model.TermScoreProtos.TermScoreDataset) {
          return mergeFrom((com.gtech.model.TermScoreProtos.TermScoreDataset)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gtech.model.TermScoreProtos.TermScoreDataset other) {
        if (other == com.gtech.model.TermScoreProtos.TermScoreDataset.getDefaultInstance()) return this;
        if (termScoreBuilder_ == null) {
          if (!other.termScore_.isEmpty()) {
            if (termScore_.isEmpty()) {
              termScore_ = other.termScore_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTermScoreIsMutable();
              termScore_.addAll(other.termScore_);
            }
            onChanged();
          }
        } else {
          if (!other.termScore_.isEmpty()) {
            if (termScoreBuilder_.isEmpty()) {
              termScoreBuilder_.dispose();
              termScoreBuilder_ = null;
              termScore_ = other.termScore_;
              bitField0_ = (bitField0_ & ~0x00000001);
              termScoreBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTermScoreFieldBuilder() : null;
            } else {
              termScoreBuilder_.addAllMessages(other.termScore_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getTermScoreCount(); i++) {
          if (!getTermScore(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gtech.model.TermScoreProtos.TermScoreDataset parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gtech.model.TermScoreProtos.TermScoreDataset) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .model.TermScore termScore = 1;
      private java.util.List<com.gtech.model.TermScoreProtos.TermScore> termScore_ =
        java.util.Collections.emptyList();
      private void ensureTermScoreIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          termScore_ = new java.util.ArrayList<com.gtech.model.TermScoreProtos.TermScore>(termScore_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.gtech.model.TermScoreProtos.TermScore, com.gtech.model.TermScoreProtos.TermScore.Builder, com.gtech.model.TermScoreProtos.TermScoreOrBuilder> termScoreBuilder_;

      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public java.util.List<com.gtech.model.TermScoreProtos.TermScore> getTermScoreList() {
        if (termScoreBuilder_ == null) {
          return java.util.Collections.unmodifiableList(termScore_);
        } else {
          return termScoreBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public int getTermScoreCount() {
        if (termScoreBuilder_ == null) {
          return termScore_.size();
        } else {
          return termScoreBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public com.gtech.model.TermScoreProtos.TermScore getTermScore(int index) {
        if (termScoreBuilder_ == null) {
          return termScore_.get(index);
        } else {
          return termScoreBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public Builder setTermScore(
          int index, com.gtech.model.TermScoreProtos.TermScore value) {
        if (termScoreBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTermScoreIsMutable();
          termScore_.set(index, value);
          onChanged();
        } else {
          termScoreBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public Builder setTermScore(
          int index, com.gtech.model.TermScoreProtos.TermScore.Builder builderForValue) {
        if (termScoreBuilder_ == null) {
          ensureTermScoreIsMutable();
          termScore_.set(index, builderForValue.build());
          onChanged();
        } else {
          termScoreBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public Builder addTermScore(com.gtech.model.TermScoreProtos.TermScore value) {
        if (termScoreBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTermScoreIsMutable();
          termScore_.add(value);
          onChanged();
        } else {
          termScoreBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public Builder addTermScore(
          int index, com.gtech.model.TermScoreProtos.TermScore value) {
        if (termScoreBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTermScoreIsMutable();
          termScore_.add(index, value);
          onChanged();
        } else {
          termScoreBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public Builder addTermScore(
          com.gtech.model.TermScoreProtos.TermScore.Builder builderForValue) {
        if (termScoreBuilder_ == null) {
          ensureTermScoreIsMutable();
          termScore_.add(builderForValue.build());
          onChanged();
        } else {
          termScoreBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public Builder addTermScore(
          int index, com.gtech.model.TermScoreProtos.TermScore.Builder builderForValue) {
        if (termScoreBuilder_ == null) {
          ensureTermScoreIsMutable();
          termScore_.add(index, builderForValue.build());
          onChanged();
        } else {
          termScoreBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public Builder addAllTermScore(
          java.lang.Iterable<? extends com.gtech.model.TermScoreProtos.TermScore> values) {
        if (termScoreBuilder_ == null) {
          ensureTermScoreIsMutable();
          super.addAll(values, termScore_);
          onChanged();
        } else {
          termScoreBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public Builder clearTermScore() {
        if (termScoreBuilder_ == null) {
          termScore_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          termScoreBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public Builder removeTermScore(int index) {
        if (termScoreBuilder_ == null) {
          ensureTermScoreIsMutable();
          termScore_.remove(index);
          onChanged();
        } else {
          termScoreBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public com.gtech.model.TermScoreProtos.TermScore.Builder getTermScoreBuilder(
          int index) {
        return getTermScoreFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public com.gtech.model.TermScoreProtos.TermScoreOrBuilder getTermScoreOrBuilder(
          int index) {
        if (termScoreBuilder_ == null) {
          return termScore_.get(index);  } else {
          return termScoreBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public java.util.List<? extends com.gtech.model.TermScoreProtos.TermScoreOrBuilder> 
           getTermScoreOrBuilderList() {
        if (termScoreBuilder_ != null) {
          return termScoreBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(termScore_);
        }
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public com.gtech.model.TermScoreProtos.TermScore.Builder addTermScoreBuilder() {
        return getTermScoreFieldBuilder().addBuilder(
            com.gtech.model.TermScoreProtos.TermScore.getDefaultInstance());
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public com.gtech.model.TermScoreProtos.TermScore.Builder addTermScoreBuilder(
          int index) {
        return getTermScoreFieldBuilder().addBuilder(
            index, com.gtech.model.TermScoreProtos.TermScore.getDefaultInstance());
      }
      /**
       * <code>repeated .model.TermScore termScore = 1;</code>
       */
      public java.util.List<com.gtech.model.TermScoreProtos.TermScore.Builder> 
           getTermScoreBuilderList() {
        return getTermScoreFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.gtech.model.TermScoreProtos.TermScore, com.gtech.model.TermScoreProtos.TermScore.Builder, com.gtech.model.TermScoreProtos.TermScoreOrBuilder> 
          getTermScoreFieldBuilder() {
        if (termScoreBuilder_ == null) {
          termScoreBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.gtech.model.TermScoreProtos.TermScore, com.gtech.model.TermScoreProtos.TermScore.Builder, com.gtech.model.TermScoreProtos.TermScoreOrBuilder>(
                  termScore_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          termScore_ = null;
        }
        return termScoreBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:model.TermScoreDataset)
    }

    static {
      defaultInstance = new TermScoreDataset(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:model.TermScoreDataset)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_model_TermScore_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_TermScore_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_model_TermScoreDataset_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_TermScoreDataset_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020term_score.proto\022\005model\"(\n\tTermScore\022\014" +
      "\n\004name\030\001 \002(\t\022\r\n\005score\030\002 \002(\005\"7\n\020TermScore" +
      "Dataset\022#\n\ttermScore\030\001 \003(\0132\020.model.TermS" +
      "coreB\"\n\017com.gtech.modelB\017TermScoreProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_model_TermScore_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_model_TermScore_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_model_TermScore_descriptor,
              new java.lang.String[] { "Name", "Score", });
          internal_static_model_TermScoreDataset_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_model_TermScoreDataset_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_model_TermScoreDataset_descriptor,
              new java.lang.String[] { "TermScore", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
